"""Map structured findings to GitHub review comments and a summary review.

`map_findings` turns findings into inline-comment payloads, skipping any whose
line is not part of the diff (GitHub rejects those). `build_summary` renders an
aggregated markdown comment — including any findings that could not be inlined,
so nothing is silently lost. `post_review` ties it together into one API call.
"""

from __future__ import annotations

from app.github.client import GitHubClient
from app.github.diff import ParsedDiff
from app.review.schema import Finding, PassType, ReviewResult, Severity, Verdict

SEVERITY_EMOJI: dict[Severity, str] = {
    Severity.critical: "🛑",
    Severity.high: "🔴",
    Severity.medium: "🟠",
    Severity.low: "🟡",
    Severity.info: "🔵",
}

PASS_LABEL: dict[PassType, str] = {
    PassType.correctness: "Correctness",
    PassType.security: "Security",
    PassType.style: "Style",
    PassType.tests: "Tests",
}

_VERDICT_EVENT: dict[Verdict, str] = {
    Verdict.approve: "APPROVE",
    Verdict.comment: "COMMENT",
    Verdict.request_changes: "REQUEST_CHANGES",
}

_VERDICT_HEADLINE: dict[Verdict, str] = {
    Verdict.approve: "✅ Approved — no blocking issues found",
    Verdict.comment: "💬 Commented — non-blocking suggestions",
    Verdict.request_changes: "🔴 Changes requested",
}


def verdict_to_event(verdict: Verdict) -> str:
    return _VERDICT_EVENT[verdict]


def format_comment_body(finding: Finding) -> str:
    emoji = SEVERITY_EMOJI[finding.severity]
    label = PASS_LABEL[finding.pass_type]
    lines = [
        f"**{emoji} {finding.severity.value.upper()} · {label}** — {finding.title}",
        "",
        finding.message,
    ]
    # GitHub's applicable ```suggestion block only works for single lines.
    if finding.suggestion and not (finding.end_line and finding.end_line > finding.line):
        lines += ["", "```suggestion", finding.suggestion.rstrip("\n"), "```"]
    return "\n".join(lines)


def finding_to_comment(finding: Finding, diff: ParsedDiff) -> dict | None:
    """Build a GitHub inline-comment payload, or None if not commentable."""
    dfile = diff.get(finding.file)
    if dfile is None or not dfile.is_commentable(finding.line, finding.side):
        return None

    comment: dict = {"path": finding.file, "body": format_comment_body(finding)}
    end = finding.end_line
    if end and end > finding.line and dfile.is_commentable(end, finding.side):
        # Multi-line comment: `line` is the last line, `start_line` the first.
        comment["start_line"] = finding.line
        comment["start_side"] = finding.side
        comment["line"] = end
        comment["side"] = finding.side
    else:
        comment["line"] = finding.line
        comment["side"] = finding.side
    return comment


def map_findings(
    findings: list[Finding], diff: ParsedDiff
) -> tuple[list[dict], list[Finding]]:
    """Split findings into inline-comment payloads and non-inlinable ones."""
    inline: list[dict] = []
    skipped: list[Finding] = []
    for f in findings:
        payload = finding_to_comment(f, diff)
        if payload is not None:
            inline.append(payload)
        else:
            skipped.append(f)
    return inline, skipped


def build_summary(result: ReviewResult, skipped: list[Finding]) -> str:
    """Render the aggregated summary comment."""
    lines = [
        "## 🤖 AI PR Review",
        "",
        f"**{_VERDICT_HEADLINE[result.verdict]}**",
        "",
        "| Severity | Count |",
        "| --- | --- |",
    ]
    for sev in (Severity.critical, Severity.high, Severity.medium, Severity.low, Severity.info):
        count = result.counts.get(sev.value, 0)
        if count:
            lines.append(f"| {SEVERITY_EMOJI[sev]} {sev.value} | {count} |")
    if not result.findings:
        lines.append("| — | 0 |")

    lines += ["", f"**{len(result.findings)}** finding(s) total."]

    if skipped:
        lines += [
            "",
            "<details><summary>Findings outside the diff "
            f"({len(skipped)})</summary>",
            "",
        ]
        for f in skipped:
            emoji = SEVERITY_EMOJI[f.severity]
            lines.append(
                f"- {emoji} `{f.file}:{f.line}` — **{f.title}**: {f.message}"
            )
        lines += ["", "</details>"]

    lines += ["", "<sub>Generated by the AI GitHub PR Reviewer.</sub>"]
    return "\n".join(lines)


def post_review(
    client: GitHubClient,
    owner: str,
    repo: str,
    number: int,
    result: ReviewResult,
    diff: ParsedDiff,
    *,
    head_sha: str | None = None,
) -> dict:
    """Post the aggregated review (summary + inline comments) to the PR."""
    inline, skipped = map_findings(result.findings, diff)
    body = build_summary(result, skipped)
    event = verdict_to_event(result.verdict)
    return client.create_review(
        owner,
        repo,
        number,
        body=body,
        event=event,
        comments=inline,
        commit_id=head_sha,
    )
